"""
Search module: text search, vector search, and hybrid (RRF) search
over the music knowledge base. Same pattern as LLM Zoomcamp HW3.
"""

import json
from pathlib import Path

import numpy as np
from minsearch import Index, VectorSearch
from embedder import Embedder

_embedder = None
def _get_embedder():
    global _embedder
    if _embedder is None:
        _embedder = Embedder()
    return _embedder

DATA_PATH       = Path(__file__).resolve().parent.parent / "data" / "docs.json"
EMBEDDINGS_PATH = Path(__file__).resolve().parent.parent / "data" / "embeddings.npy"


def load_docs():
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def build_text_index(docs):
    index = Index(text_fields=["chunk", "topic"], keyword_fields=[])
    index.fit(docs)
    return index


def build_vector_index(docs):
    """ONNX-based vector index.

    If data/embeddings.npy exists (generated by src/build_embeddings.py),
    it is loaded directly — startup takes ~1 second instead of ~10 minutes.
    If not, embeddings are computed from scratch (backward-compatible fallback).
    """
    embedder = _get_embedder()

    if EMBEDDINGS_PATH.exists():
        print(f"Loading precomputed embeddings from {EMBEDDINGS_PATH} ...")
        embeddings = np.load(EMBEDDINGS_PATH)
    else:
        print("No precomputed embeddings found — computing from scratch (this may take several minutes)...")
        print("Tip: run 'uv run python src/build_embeddings.py' once to speed up future startups.")
        texts = [d["chunk"] for d in docs]
        embeddings = embedder.encode_batch(texts)

    vindex = VectorSearch(keyword_fields=[])
    vindex.fit(embeddings, docs)
    return vindex, embedder


def text_search(index, query, num_results=5):
    return index.search(query, num_results=num_results)


def vector_search(vindex, embedder, query, num_results=5):
    q_vec = embedder.encode(query)
    return vindex.search(q_vec, num_results=num_results)


def hybrid_search(index, vindex, embedder, query, num_results=5, k=60):
    """Reciprocal Rank Fusion of text + vector results."""
    text_results = text_search(index, query, num_results=10)
    vec_results = vector_search(vindex, embedder, query, num_results=10)

    scores = {}
    doc_lookup = {}

    for rank, doc in enumerate(text_results):
        doc_id = doc["id"]
        doc_lookup[doc_id] = doc
        scores[doc_id] = scores.get(doc_id, 0) + 1 / (k + rank + 1)

    for rank, doc in enumerate(vec_results):
        doc_id = doc["id"]
        doc_lookup[doc_id] = doc
        scores[doc_id] = scores.get(doc_id, 0) + 1 / (k + rank + 1)

    ranked_ids = sorted(scores, key=scores.get, reverse=True)[:num_results]
    return [doc_lookup[i] for i in ranked_ids]


if __name__ == "__main__":
    docs = load_docs()
    print(f"Loaded {len(docs)} chunks")
    index = build_text_index(docs)
    vindex, embedder = build_vector_index(docs)

    q = "Who were the members of the Beatles?"
    print("\nText search:")
    for d in text_search(index, q, 3):
        print(" -", d["topic"], "|", d["chunk"][:80])

    print("\nHybrid search:")
    for d in hybrid_search(index, vindex, embedder, q, 3):
        print(" -", d["topic"], "|", d["chunk"][:80])
